p1 = str(input())
gpa1 = float(input())
p2 = str(input())
gpa2 = float(input())
p3 = str(input())
gpa3 = float(input())
p4 = str(input())
gpa4 = float(input())
agpa = (gpa1 + gpa2 + gpa3 + gpa4) / 4
print(p1, p2, p3, p4, 'average gpa:', agpa)